# Generated by Django 3.2.6 on 2021-08-19 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_traders', '0002_coins'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coins',
            options={'verbose_name_plural': 'coins'},
        ),
    ]
