# Generated by Django 3.2.6 on 2021-08-20 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_traders', '0008_auto_20210820_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crypto_traders.bank'),
            preserve_default=False,
        ),
    ]
