# Generated by Django 3.2.6 on 2021-08-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_traders', '0009_asset_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='high_24h',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='low_24h',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='market_cap',
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='asset',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bank',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='coins',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='coins',
            name='high_24h',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='coins',
            name='low_24h',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
